apiVersion: v1
kind: Service
metadata:
  name: bagnoli-monitor
  namespace: bagnoli-monitor
  labels:
    app: bagnoli-monitor
spec:
  type: ClusterIP
  selector:
    app: bagnoli-monitor
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
